### ISSUE TITLE
Can you mention the versions of six and pbr libraries. By running python setup.py install the following error occurs.

### ISSUE THREAD

**Issue by graviraja** [irshadbhat/python-converter-indic#3]
![image](https://user-images.githubusercontent.com/7556119/33761587-98f62330-dc2f-11e7-933e-26734744ae12.png)

**Comment by irshadbhat** [comment]
I have updated the setup file. See if this solves the issue.

**Comment by graviraja** [comment]
I am able to install in MacOS and Ubuntu systems. But in Windows it is throwing codecs error.
![image](https://user-images.githubusercontent.com/7556119/34041120-cb9cd210-e1bc-11e7-8f4f-1bf6eb1d1fef.png)

**Comment by harmanpreet93** [comment]
@irshadbhat @graviraja any update on how to solve the codec error on windows? I'm facing the same issue in python 3.6.4. Although it works fine in python 2.7.x.

**Comment by Farrukhbala** [comment]
I am also facing the same issue. I am creating an app and I want this converter badly.
I am using Python 3.6.4.

**Comment by irshadbhat** [comment]
I mostly work on linux. But recently I installed this package on a windows system (both python2+ and 3+ versions) and the installation was complete without any issue. I once faced a similar issue on an ubuntu system and the issue was fixed by updating the setuptools. Try to update the python-setuptools. Maybe that will fix the issue.

Do mention the setuptools version before and after the update. You can find the setuptools version using the below commands

```
import setuptools
print setuptools.__version__
```
